# Generated by Django 5.1.4 on 2026-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assignment', 'Program assigned'), ('reminder', 'Reminder'), ('progress', 'Progress'), ('assessment', 'Assessment'), ('message', 'Message')], max_length=20),
        ),
    ]
