# Generated by Django 5.1.4 on 2026-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event')], default='NEWS', max_length=8)),
                ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('TRAINERS', 'Trainers'), ('PATIENTS', 'Patients')], default='ALL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('image_url', models.URLField(blank=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('pinned', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
