from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from assessments.models import Assessment
from training.models import Exercise, ProgramAssignment, ProgramExercise, TrainingProgram
from training.serializers import ProgramAssignmentSerializer

from .models import AssistantMessage
from . import recommend
from .serializers import AssistantMessageSerializer


class MessagesView(APIView):
    """List the caller's assistant conversation, or clear it."""

    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        msgs = AssistantMessage.objects.filter(user=request.user)
        return Response(AssistantMessageSerializer(msgs, many=True).data)

    def delete(self, request):
        AssistantMessage.objects.filter(user=request.user).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ChatView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        content = (request.data.get("content") or "").strip()
        if not content:
            return Response({"detail": "Message is empty."}, status=400)

        AssistantMessage.objects.create(
            user=request.user, sender=AssistantMessage.Sender.USER, content=content
        )

        history = list(
            AssistantMessage.objects.filter(
                user=request.user, sender=AssistantMessage.Sender.USER
            ).values_list("content", flat=True)
        )

        latest_pain = None
        last_assessment = (
            Assessment.objects.filter(patient=request.user).order_by("-created_at").first()
        )
        if last_assessment:
            latest_pain = last_assessment.pain_level

        reply, proposal = recommend.generate(history, latest_pain=latest_pain, request=request)

        msg = AssistantMessage.objects.create(
            user=request.user,
            sender=AssistantMessage.Sender.ASSISTANT,
            content=reply,
            proposal=proposal,
        )
        return Response(AssistantMessageSerializer(msg).data, status=201)


class AcceptPlanView(APIView):
    """Turn an AI proposal into a real program assigned to the patient."""

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        if not request.user.is_patient:
            return Response({"detail": "Only patients can accept a plan."}, status=403)

        name = (request.data.get("name") or "My AI plan").strip()[:150]
        items = request.data.get("exercises") or []
        if not items:
            return Response({"detail": "No exercises in the plan."}, status=400)

        program = TrainingProgram.objects.create(
            created_by=None,
            is_template=False,
            name=name,
            description="Generated by the SmartKineto AI assistant.",
        )
        order = 0
        for item in items:
            ex = Exercise.objects.filter(id=item.get("id")).first()
            if not ex:
                continue
            ProgramExercise.objects.create(
                program=program,
                exercise=ex,
                order=order,
                sets=int(item.get("sets") or 2),
                reps=int(item.get("reps") or 10),
            )
            order += 1

        if order == 0:
            program.delete()
            return Response({"detail": "None of the exercises were found."}, status=400)

        assignment, _ = ProgramAssignment.objects.get_or_create(
            program=program,
            patient=request.user,
            defaults={"assigned_by": None, "status": ProgramAssignment.Status.ACTIVE},
        )
        return Response(ProgramAssignmentSerializer(assignment).data, status=201)
