# Generated by Django 5.1.4 on 2026-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_exercise_is_template_trainingprogram_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='review_status',
            field=models.CharField(choices=[('NONE', 'Not submitted'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='review_status',
            field=models.CharField(choices=[('NONE', 'Not submitted'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
    ]
