# Generated by Django 5.1.4 on 2026-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_exercise_is_public_exercise_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12),
        ),
    ]
