# Generated by Django 5.1.4 on 2026-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_programassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='stage',
            field=models.CharField(choices=[('EARLY_STAGE', 'Early stage'), ('ADVANCED_STAGE', 'Advanced stage')], default='ADVANCED_STAGE', max_length=16),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_reps',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tracking_method',
            field=models.CharField(choices=[('HARDWARE_WAND', 'Hardware wand'), ('CAMERA_POSE', 'Camera pose'), ('MANUAL', 'Manual / no tracking')], default='CAMERA_POSE', max_length=16),
        ),
    ]
