# Generated by Django 5.1.4 on 2026-07-03 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0005_exercise_stage_exercise_target_reps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WandReferenceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frames', models.JSONField()),
                ('sample_count', models.PositiveIntegerField(default=100)),
                ('rep_count', models.PositiveIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wand_templates', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wand_template', to='training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WandSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_reps', models.PositiveIntegerField()),
                ('valid_reps', models.PositiveIntegerField(default=0)),
                ('invalid_reps', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wand_sessions', to='training.programassignment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wand_sessions', to='training.exercise')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='wand_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WandRepetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('frames', models.JSONField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('movement_similarity', models.FloatField()),
                ('rom_similarity', models.FloatField()),
                ('tempo_similarity', models.FloatField()),
                ('smoothness_score', models.FloatField()),
                ('graph_score', models.FloatField()),
                ('duration_ratio', models.FloatField()),
                ('is_valid', models.BooleanField()),
                ('rejection_reason', models.CharField(blank=True, choices=[('TOO_SHORT', 'Too_Short'), ('TOO_FAST', 'Too_Fast'), ('TOO_SLOW', 'Too_Slow'), ('UNSTABLE', 'Unstable'), ('WRONG_DIRECTION', 'Wrong_Direction'), ('INCOMPLETE', 'Incomplete'), ('LOW_SIMILARITY', 'Low_Similarity')], max_length=20)),
                ('preview_points', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='wand.wandsession')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('session', 'index')},
            },
        ),
    ]
